version: '3.4'

services:
  #Database
  mysql_server:
    container_name: mysql_server
    hostname: mysql_server
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
        - 3306:3306
    volumes:
        - ./init:/docker-entrypoint-initdb.d
    environment:
        MYSQL_ROOT_PASSWORD: Start123!
        MYSQL_DATABASE: estate_agency_db
  #API
  realestateagencyapi:
    container_name: real_estate_api
    hostname: real_estate_api
    image: ${DOCKER_REGISTRY-}realestateagencyapi
    build:
      context: .
      dockerfile: RealEstateAgencyAPI/Dockerfile
    ports:
        - 5000:80
        - 5001:443
    links:
        - mysql_server:mysql_server
    depends_on:
        - mysql_server
  #Frontend
  realestateagencyfrontend:
    container_name: real_estate_frontend
    hostname: real_estate_frontend
    image: ${DOCKER_REGISTRY-}realestateagencyfrontend
    ports:
        - 3000:3000
    links:
        - realestateagencyapi:real_estate_agency_api